version: '3'

services:
  mysql:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Root
      MYSQL_DATABASE: movies
      MYSQL_USER: vishal
      MYSQL_PASSWORD: vishal
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
