version: '3'

services:
  mysql:
    image: mysql:8.0.36
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: Root
      MYSQL_DATABASE: movies
      MYSQL_USER: vishal
      MYSQL_PASSWORD: Vishal@123
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    # environment:
    #   RABBITMQ_DEFAULT_USER: admin
    #   RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
  phpmyadmin:
    image: phpmyadmin:5.2.1
    links:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Vishal@123
    
  
volumes:
  mysql_data:  
  rabbitmq_data:        
    # driver: local